// apps/react-vdom/src/components/KpiHeader.js
import { jsxs as _jsxs } from "react/jsx-runtime";
import { useMemo } from 'react';
export default function KpiHeader({ rows }) {
    const metrics = useMemo(() => {
        const revenue = rows.reduce((a, r) => a + r.price * r.qty, 0);
        const units = rows.reduce((a, r) => a + r.qty, 0);
        const avgPrice = units ? revenue / units : 0;
        return { revenue, units, avgPrice };
    }, [rows]);
    return (_jsxs("div", { children: [_jsxs("span", { "data-test": "kpi-revenue", children: ["Revenue: ", metrics.revenue.toFixed(2)] }), _jsxs("span", { "data-test": "kpi-units", children: [" Units: ", metrics.units] }), _jsxs("span", { "data-test": "kpi-avg", children: [" Avg Price: ", metrics.avgPrice.toFixed(2)] })] }));
}

// apps/solid-signals/src/components/KpiHeader.tsx
import { Component, createMemo } from 'solid-js';
import { Row } from 'shared-data';

interface Props { rows: () => Row[]; }

const KpiHeader: Component<Props> = (props) => {
  const metrics = createMemo(() => {
    const r = props.rows();
    const revenue = r.reduce((a, row) => a + row.price * row.qty, 0);
    const units = r.reduce((a, row) => a + row.qty, 0);
    const avgPrice = units ? revenue / units : 0;
    return { revenue, units, avgPrice };
  });
  return (
    <div>
      <span data-test="kpi-revenue">Revenue: {metrics().revenue.toFixed(2)}</span>
      <span data-test="kpi-units"> Units: {metrics().units}</span>
      <span data-test="kpi-avg"> Avg Price: {metrics().avgPrice.toFixed(2)}</span>
    </div>
  );
};
export default KpiHeader;
